/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.SimpleTimeZone;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.AppoinmentPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.AppoinmentPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.AttendancePanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.ChangeUserPasswordPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.DoctorPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.HospitalPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.MakeNewAppointmentPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.MakeNewSchedule;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.MakePaymentPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.MarkAppointmentPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.NewSchedulePanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.PatientPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.PaymentPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.SchedulePanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.SpecialityPanel;
import lk.ijse.gdse41.doctorchannelingsystem.view.panel.ViewAppointmentPanel;

/**
 *
 * @author Binura Salindra
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setSize(1366,768);
        loadDate();
        setTime();
    }
    
    public void loadDate(){
        Date today=new Date();
        DateFormat df=DateFormat.getDateInstance(DateFormat.FULL, Locale.ROOT);
        String date=df.format(today);
        lblDate.setText(date);
    }
    public void setTime(){
        Timer t=new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar cal=Calendar.getInstance();
                SimpleDateFormat df=new SimpleDateFormat("hh:mm:ss a");
                lblNewTime.setText(df.format(cal.getTime()));
            }
        });
        t.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAppointmentSettings = new org.jdesktop.swingx.JXLabel();
        lblPatients = new org.jdesktop.swingx.JXLabel();
        lblDoctors = new org.jdesktop.swingx.JXLabel();
        lblMakeAppointment = new org.jdesktop.swingx.JXLabel();
        lblViewAppointment = new org.jdesktop.swingx.JXLabel();
        lblViewSchedule = new org.jdesktop.swingx.JXLabel();
        lblScheduleSettings = new org.jdesktop.swingx.JXLabel();
        lblPayments = new org.jdesktop.swingx.JXLabel();
        lblSpecialities = new org.jdesktop.swingx.JXLabel();
        lblHospital = new org.jdesktop.swingx.JXLabel();
        lblMarkAttendance = new org.jdesktop.swingx.JXLabel();
        jPanel3 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblMaximise = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        lblNewTime = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        lblAppointmentSettings.setBorder(dropShadowBorder1);
        lblAppointmentSettings.setForeground(new java.awt.Color(255, 255, 255));
        lblAppointmentSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAppointmentSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Horizontal Settings Mixer_26px.png"))); // NOI18N
        lblAppointmentSettings.setText("Appointment Settings");
        lblAppointmentSettings.setToolTipText("Click to change appointment details");
        lblAppointmentSettings.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAppointmentSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAppointmentSettingsMouseClicked(evt);
            }
        });
        jPanel2.add(lblAppointmentSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        lblPatients.setBorder(dropShadowBorder2);
        lblPatients.setForeground(new java.awt.Color(255, 255, 255));
        lblPatients.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPatients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/patients_26px.png"))); // NOI18N
        lblPatients.setText("Patients");
        lblPatients.setToolTipText("Click to view,add and change patients' details");
        lblPatients.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPatientsMouseClicked(evt);
            }
        });
        jPanel2.add(lblPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        lblDoctors.setBorder(dropShadowBorder3);
        lblDoctors.setForeground(new java.awt.Color(255, 255, 255));
        lblDoctors.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDoctors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Medical Doctor_26px.png"))); // NOI18N
        lblDoctors.setText("Doctors");
        lblDoctors.setToolTipText("Click to view,add and change doctors' details");
        lblDoctors.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDoctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoctorsMouseClicked(evt);
            }
        });
        jPanel2.add(lblDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        lblMakeAppointment.setBorder(dropShadowBorder4);
        lblMakeAppointment.setForeground(new java.awt.Color(255, 255, 255));
        lblMakeAppointment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMakeAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/make Appointmet_26px.png"))); // NOI18N
        lblMakeAppointment.setText("Make Appointment");
        lblMakeAppointment.setToolTipText("Click to Make New Appointment");
        lblMakeAppointment.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMakeAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMakeAppointmentMouseClicked(evt);
            }
        });
        jPanel2.add(lblMakeAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShowLeftShadow(true);
        dropShadowBorder5.setShowTopShadow(true);
        lblViewAppointment.setBorder(dropShadowBorder5);
        lblViewAppointment.setForeground(new java.awt.Color(255, 255, 255));
        lblViewAppointment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Appointment Reminders_26px.png"))); // NOI18N
        lblViewAppointment.setText("View Appointments");
        lblViewAppointment.setToolTipText("Click to View Appointments");
        lblViewAppointment.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblViewAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewAppointmentMouseClicked(evt);
            }
        });
        jPanel2.add(lblViewAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setShowLeftShadow(true);
        dropShadowBorder6.setShowTopShadow(true);
        lblViewSchedule.setBorder(dropShadowBorder6);
        lblViewSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lblViewSchedule.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Schedule_26px.png"))); // NOI18N
        lblViewSchedule.setText("View Schedule");
        lblViewSchedule.setToolTipText("Click to view schedule");
        lblViewSchedule.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblViewSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewScheduleMouseClicked(evt);
            }
        });
        jPanel2.add(lblViewSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder7 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder7.setShowLeftShadow(true);
        dropShadowBorder7.setShowTopShadow(true);
        lblScheduleSettings.setBorder(dropShadowBorder7);
        lblScheduleSettings.setForeground(new java.awt.Color(255, 255, 255));
        lblScheduleSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblScheduleSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Horizontal Settings Mixer_26px.png"))); // NOI18N
        lblScheduleSettings.setText("Schedule Settings");
        lblScheduleSettings.setToolTipText("Click to change schedule details");
        lblScheduleSettings.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblScheduleSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScheduleSettingsMouseClicked(evt);
            }
        });
        jPanel2.add(lblScheduleSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder8 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder8.setShowLeftShadow(true);
        dropShadowBorder8.setShowTopShadow(true);
        lblPayments.setBorder(dropShadowBorder8);
        lblPayments.setForeground(new java.awt.Color(255, 255, 255));
        lblPayments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Coins_26px.png"))); // NOI18N
        lblPayments.setText("Payments");
        lblPayments.setToolTipText("Click to do and view payments");
        lblPayments.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentsMouseClicked(evt);
            }
        });
        jPanel2.add(lblPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder9 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder9.setShowLeftShadow(true);
        dropShadowBorder9.setShowTopShadow(true);
        lblSpecialities.setBorder(dropShadowBorder9);
        lblSpecialities.setForeground(new java.awt.Color(255, 255, 255));
        lblSpecialities.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSpecialities.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Diploma 1_26px.png"))); // NOI18N
        lblSpecialities.setText("Specialities");
        lblSpecialities.setToolTipText("Click to add and change speciality details");
        lblSpecialities.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSpecialities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpecialitiesMouseClicked(evt);
            }
        });
        jPanel2.add(lblSpecialities, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder10 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder10.setShowLeftShadow(true);
        dropShadowBorder10.setShowTopShadow(true);
        lblHospital.setBorder(dropShadowBorder10);
        lblHospital.setForeground(new java.awt.Color(255, 255, 255));
        lblHospital.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Hospital 3_26px.png"))); // NOI18N
        lblHospital.setText("Hospitals");
        lblHospital.setToolTipText("Click to add and change hospital details");
        lblHospital.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHospitalMouseClicked(evt);
            }
        });
        jPanel2.add(lblHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 250, 50));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder11 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder11.setShowLeftShadow(true);
        dropShadowBorder11.setShowTopShadow(true);
        lblMarkAttendance.setBorder(dropShadowBorder11);
        lblMarkAttendance.setForeground(new java.awt.Color(255, 255, 255));
        lblMarkAttendance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMarkAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/True False_26px.png"))); // NOI18N
        lblMarkAttendance.setText("Mark Attendance");
        lblMarkAttendance.setToolTipText("Click to mark and view appointment attendance");
        lblMarkAttendance.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMarkAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMarkAttendanceMouseClicked(evt);
            }
        });
        jPanel2.add(lblMarkAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 250, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Close Window_30pxnn.png"))); // NOI18N
        lblClose.setToolTipText("Close");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Minimize Window_30pxnn.png"))); // NOI18N
        lblMinimize.setToolTipText("Minimize");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblLogo.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 0, 0));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/logo-medicity.jpg"))); // NOI18N
        lblLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDate.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaximise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Maximize Window_30pxnn.png"))); // NOI18N
        lblMaximise.setToolTipText("Maximize");
        lblMaximise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaximiseMouseClicked(evt);
            }
        });

        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/logOut26px.png"))); // NOI18N
        lblLogOut.setToolTipText("Logout");
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
        });

        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/PasswordSettings_26px.png"))); // NOI18N
        lblSettings.setToolTipText("Settings");
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
        });

        lblNewTime.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblNewTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNewTime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMinimize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaximise)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClose)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMaximise, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Main Wall1.png"))); // NOI18N

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAppointmentSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppointmentSettingsMouseClicked
        AppoinmentPanel ap1=new AppoinmentPanel();
        ap1.setSize(pnlMain.getSize());
        pnlMain.removeAll();
        pnlMain.add(ap1);
        pnlMain.revalidate();
        pnlMain.repaint();
        ap1.show();
    }//GEN-LAST:event_lblAppointmentSettingsMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
      this.setState(MainFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblPatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPatientsMouseClicked
       PatientPanel p1=new PatientPanel();
       p1.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(p1);
       pnlMain.revalidate();
       pnlMain.repaint();
       p1.show();
    }//GEN-LAST:event_lblPatientsMouseClicked

    private void lblDoctorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctorsMouseClicked
       DoctorPanel d1=new DoctorPanel();
       d1.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(d1);
       pnlMain.revalidate();
       pnlMain.repaint();
       d1.show();
    }//GEN-LAST:event_lblDoctorsMouseClicked

    private void lblMakeAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeAppointmentMouseClicked
       MakeNewAppointmentPanel s1=new MakeNewAppointmentPanel();
       s1.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(s1);
       pnlMain.revalidate();
       pnlMain.repaint();
       s1.show();
    }//GEN-LAST:event_lblMakeAppointmentMouseClicked

    private void lblViewAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAppointmentMouseClicked
       ViewAppointmentPanel s1=new ViewAppointmentPanel();
       s1.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(s1);
       pnlMain.revalidate();
       pnlMain.repaint();
       s1.show();
    }//GEN-LAST:event_lblViewAppointmentMouseClicked

    private void lblViewScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewScheduleMouseClicked
       SchedulePanel sc=new SchedulePanel();
       sc.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(sc);
       pnlMain.revalidate();
       pnlMain.repaint();
       sc.show();
    }//GEN-LAST:event_lblViewScheduleMouseClicked

    private void lblScheduleSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleSettingsMouseClicked
       NewSchedulePanel sc=new NewSchedulePanel();
       sc.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(sc);
       pnlMain.revalidate();
       pnlMain.repaint();
       sc.show();
    }//GEN-LAST:event_lblScheduleSettingsMouseClicked

    private void lblPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentsMouseClicked
       PaymentPanel sc=new PaymentPanel();
       sc.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(sc);
       pnlMain.revalidate();
       pnlMain.repaint();
       sc.show();
    }//GEN-LAST:event_lblPaymentsMouseClicked

    private void lblSpecialitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpecialitiesMouseClicked
       SpecialityPanel sc=new SpecialityPanel();
       sc.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(sc);
       pnlMain.revalidate();
       pnlMain.repaint();
       sc.show();
    }//GEN-LAST:event_lblSpecialitiesMouseClicked

    private void lblHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHospitalMouseClicked
       HospitalPanel sc=new HospitalPanel();
       sc.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(sc);
       pnlMain.revalidate();
       pnlMain.repaint();
    }//GEN-LAST:event_lblHospitalMouseClicked

    private void lblMaximiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximiseMouseClicked
      this.setExtendedState(MainFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_lblMaximiseMouseClicked

    private void lblMarkAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarkAttendanceMouseClicked
       AttendancePanel sc=new AttendancePanel();
       sc.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(sc);
       pnlMain.revalidate();
       pnlMain.repaint();
    }//GEN-LAST:event_lblMarkAttendanceMouseClicked

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
       this.dispose();
       LogScreen lg=new LogScreen();
       lg.setVisible(true);
       
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
       ChangeUserPasswordPanel sc=new ChangeUserPasswordPanel();
       sc.setSize(pnlMain.getSize());
       pnlMain.removeAll();
       pnlMain.add(sc);
       pnlMain.revalidate();
       pnlMain.repaint();
    }//GEN-LAST:event_lblSettingsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.jdesktop.swingx.JXLabel lblAppointmentSettings;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private org.jdesktop.swingx.JXLabel lblDoctors;
    private org.jdesktop.swingx.JXLabel lblHospital;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblLogo;
    private org.jdesktop.swingx.JXLabel lblMakeAppointment;
    private org.jdesktop.swingx.JXLabel lblMarkAttendance;
    private javax.swing.JLabel lblMaximise;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblNewTime;
    private org.jdesktop.swingx.JXLabel lblPatients;
    private org.jdesktop.swingx.JXLabel lblPayments;
    private org.jdesktop.swingx.JXLabel lblScheduleSettings;
    private javax.swing.JLabel lblSettings;
    private org.jdesktop.swingx.JXLabel lblSpecialities;
    private org.jdesktop.swingx.JXLabel lblViewAppointment;
    private org.jdesktop.swingx.JXLabel lblViewSchedule;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private ActionListener ActionListener() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
