/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

/**
 *
 * @author Binura Salindra
 */
public class AppoinmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form AppoinmentPanel
     */
    public AppoinmentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblChangeAppointmentDatails = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblCancelAppointment = new javax.swing.JLabel();
        appointmentMainPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 666));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChangeAppointmentDatails.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblChangeAppointmentDatails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Edit Property_26px.png"))); // NOI18N
        lblChangeAppointmentDatails.setText("Postpone Or Change Appointment Details");
        lblChangeAppointmentDatails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeAppointmentDatailsMouseClicked(evt);
            }
        });
        jPanel1.add(lblChangeAppointmentDatails, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 20, 20));

        lblCancelAppointment.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCancelAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Trash_26px.png"))); // NOI18N
        lblCancelAppointment.setText("Cancel Appointment");
        lblCancelAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelAppointmentMouseClicked(evt);
            }
        });
        jPanel1.add(lblCancelAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        appointmentMainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/20100924fr-apple-ical-290x300.jpg"))); // NOI18N

        javax.swing.GroupLayout appointmentMainPanelLayout = new javax.swing.GroupLayout(appointmentMainPanel);
        appointmentMainPanel.setLayout(appointmentMainPanelLayout);
        appointmentMainPanelLayout.setHorizontalGroup(
            appointmentMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentMainPanelLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        appointmentMainPanelLayout.setVerticalGroup(
            appointmentMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentMainPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel3)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jPanel1.add(appointmentMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1090, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblCancelAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelAppointmentMouseClicked
       RemovelAppointmentPanel rm=new RemovelAppointmentPanel();
       rm.setSize(appointmentMainPanel.getSize());
       appointmentMainPanel.removeAll();
       appointmentMainPanel.add(rm);
       appointmentMainPanel.repaint();
       rm.show();
    }//GEN-LAST:event_lblCancelAppointmentMouseClicked

    private void lblChangeAppointmentDatailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeAppointmentDatailsMouseClicked
       ChangeAppointmentPanel1 cp=new ChangeAppointmentPanel1();
       cp.setSize(appointmentMainPanel.getSize());
       appointmentMainPanel.removeAll();
       appointmentMainPanel.add(cp);
       appointmentMainPanel.repaint();
       cp.show();
    }//GEN-LAST:event_lblChangeAppointmentDatailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appointmentMainPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCancelAppointment;
    private javax.swing.JLabel lblChangeAppointmentDatails;
    // End of variables declaration//GEN-END:variables
}
