/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.gdse41.doctorchannelingsystem.controller.ControllerFactory;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.HospitalController;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.QueryController;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.SpecialityController;
import lk.ijse.gdse41.doctorchannelingsystem.dto.HospitalDTO;
import lk.ijse.gdse41.doctorchannelingsystem.dto.SpecialityDTO;

/**
 *
 * @author Binura Salindra
 */
public class ChangeHospitalPanel extends javax.swing.JPanel {
    private QueryController ctrlQuery;
    private HospitalController ctrlHospital;

    /**
     * Creates new form ChangeSpecialityPanel
     */
    public ChangeHospitalPanel() {
        initComponents();
        ctrlQuery=(QueryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.QUERY);
        ctrlHospital=(HospitalController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.HOSPITAL);
        
        loadHospitalID();
    }
    private void loadHospitalID(){
        ArrayList<String> allHospitalId=null;
        
        try {
            allHospitalId=ctrlQuery.getAllHospitalId();
        } catch (Exception ex) {
            Logger.getLogger(ChangeHospitalPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         for (int i = 0; i < allHospitalId.size(); i++){
            cmbHospital.addItem(allHospitalId.get(i));
        }
       
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        lblHospitalId = new javax.swing.JLabel();
        lblHospital = new javax.swing.JLabel();
        cmbHospital = new com.jidesoft.swing.AutoCompletionComboBox();
        txtHospital = new javax.swing.JTextField();
        btnUpdate = new org.jdesktop.swingx.JXButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTopic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTopic.setText("Change Hospital Details");

        lblHospitalId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblHospitalId.setText("Hospital ID :");

        lblHospital.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblHospital.setText("Hospital  :");

        cmbHospital.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbHospitalItemStateChanged(evt);
            }
        });
        cmbHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHospitalActionPerformed(evt);
            }
        });

        txtHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTopic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblHospitalId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblHospital)
                        .addGap(18, 18, 18)
                        .addComponent(txtHospital)))
                .addContainerGap(752, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopic)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalId)
                    .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospital)
                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalActionPerformed

    private void cmbHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHospitalActionPerformed

    private void cmbHospitalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbHospitalItemStateChanged
       String hID=(String) cmbHospital.getSelectedItem();
        try {
            HospitalDTO hospital=ctrlQuery.getHospitalDetails(hID);
            txtHospital.setText(hospital.gethName());
        } catch (Exception ex) {
            Logger.getLogger(ChangeHospitalPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbHospitalItemStateChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String hID=(String) cmbHospital.getSelectedItem();
            HospitalDTO hh=new HospitalDTO(
                    hID,
                    txtHospital.getText());
            boolean result=ctrlHospital.update(hh);
            if(result){
                JOptionPane.showMessageDialog(this,"Update is OK...!");
            }else{
                JOptionPane.showMessageDialog(this,"Update is failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(ChangeHospitalPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnUpdate;
    private com.jidesoft.swing.AutoCompletionComboBox cmbHospital;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblHospitalId;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JTextField txtHospital;
    // End of variables declaration//GEN-END:variables
}
