/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.gdse41.doctorchannelingsystem.controller.ControllerFactory;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.QueryController;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.SpecialityController;
import lk.ijse.gdse41.doctorchannelingsystem.dto.SpecialityDTO;

/**
 *
 * @author Binura Salindra
 */
public class ChangeSpecialityPanel extends javax.swing.JPanel {
    private QueryController ctrlQuery;
    private SpecialityController ctrlSpeciality;

    /**
     * Creates new form ChangeSpecialityPanel
     */
    public ChangeSpecialityPanel() {
        initComponents();
        ctrlQuery=(QueryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.QUERY);
        ctrlSpeciality=(SpecialityController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SPECIALITY);
        
        loadSpecialityID();
    }
    private void loadSpecialityID(){
        ArrayList<String> allSpecialityId=null;
        
        try {
            allSpecialityId=ctrlQuery.getAllSpecialityId();
        } catch (Exception ex) {
            Logger.getLogger(ChangeSpecialityPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         for (int i = 0; i < allSpecialityId.size(); i++){
            cmbSpeciality.addItem(allSpecialityId.get(i));
        }
       
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        lblSpecialityID = new javax.swing.JLabel();
        lblSpecialityType = new javax.swing.JLabel();
        cmbSpeciality = new com.jidesoft.swing.AutoCompletionComboBox();
        txtSpeciality = new javax.swing.JTextField();
        btnUpdate = new org.jdesktop.swingx.JXButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTopic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTopic.setText("Change Speciality Details");

        lblSpecialityID.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSpecialityID.setText("Speciality ID :");

        lblSpecialityType.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSpecialityType.setText("Speciality  :");

        cmbSpeciality.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSpecialityItemStateChanged(evt);
            }
        });
        cmbSpeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSpecialityActionPerformed(evt);
            }
        });

        txtSpeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialityActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTopic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblSpecialityID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblSpecialityType)
                        .addGap(18, 18, 18)
                        .addComponent(txtSpeciality)))
                .addContainerGap(744, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopic)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecialityID)
                    .addComponent(cmbSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecialityType)
                    .addComponent(txtSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSpecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialityActionPerformed

    private void cmbSpecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSpecialityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSpecialityActionPerformed

    private void cmbSpecialityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSpecialityItemStateChanged
       String spID=(String) cmbSpeciality.getSelectedItem();
        try {
            SpecialityDTO speciality=ctrlQuery.getSpecialityDetails(spID);
            txtSpeciality.setText(speciality.getSpType());
        } catch (Exception ex) {
            Logger.getLogger(ChangeSpecialityPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbSpecialityItemStateChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String spID=(String) cmbSpeciality.getSelectedItem();
            SpecialityDTO sp=new SpecialityDTO(
                    spID,
                    txtSpeciality.getText());
            boolean result=ctrlSpeciality.update(sp);
            if(result){
                JOptionPane.showMessageDialog(this,"Update is OK...!");
            }else{
                JOptionPane.showMessageDialog(this,"Update is failed");
            }
        } catch (Exception ex) {
            Logger.getLogger(ChangeSpecialityPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnUpdate;
    private com.jidesoft.swing.AutoCompletionComboBox cmbSpeciality;
    private javax.swing.JLabel lblSpecialityID;
    private javax.swing.JLabel lblSpecialityType;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JTextField txtSpeciality;
    // End of variables declaration//GEN-END:variables
}
