/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.gdse41.doctorchannelingsystem.controller.ControllerFactory;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.QueryController;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.ScheduleController;
import lk.ijse.gdse41.doctorchannelingsystem.dto.ScheduleDTO;
import lk.ijse.gdse41.doctorchannelingsystem.dto.SearchQueryDTO;

/**
 *
 * @author Binura Salindra
 */
public class ChangeSchedulePanel extends javax.swing.JPanel {
    private QueryController ctrlQuery;
    private ScheduleController ctrlSchedule;

    /**
     * Creates new form ChangeSchedulePanel
     */
    public ChangeSchedulePanel() {
        initComponents();
        ctrlQuery=(QueryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.QUERY);
        ctrlSchedule=(ScheduleController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SCHEDULE);
        loadScheduleID();
    }
    private void loadScheduleID(){
        ArrayList<String> allScheduleIds=null;
        
        try {
            allScheduleIds=ctrlQuery.getScheduleId();
        } catch (Exception ex) {
            Logger.getLogger(ChangeSchedulePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
      
         for (int i = 0; i < allScheduleIds.size(); i++){
            cmbScheduleId.addItem(allScheduleIds.get(i));
        }
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        lblScheduleID = new javax.swing.JLabel();
        cmbScheduleId = new com.jidesoft.swing.AutoCompletionComboBox();
        lblDoctorName = new javax.swing.JLabel();
        lblDoctorID = new javax.swing.JLabel();
        lbldayName = new javax.swing.JLabel();
        lblTimeSlot = new javax.swing.JLabel();
        lblMaxPatientCount = new javax.swing.JLabel();
        txtDoctorName = new javax.swing.JTextField();
        txtDoctorID = new javax.swing.JTextField();
        txtDayName = new javax.swing.JTextField();
        txtTimeSlot = new javax.swing.JTextField();
        txtMaxPatientCount = new javax.swing.JTextField();
        btnUpdate = new org.jdesktop.swingx.JXButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTopic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTopic.setText("Change Schedule Details");

        lblScheduleID.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblScheduleID.setText("Schedule ID :");

        cmbScheduleId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbScheduleIdItemStateChanged(evt);
            }
        });

        lblDoctorName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDoctorName.setText("Doctor Name :");

        lblDoctorID.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDoctorID.setText("Doctor ID :");

        lbldayName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbldayName.setText("Day Name :");

        lblTimeSlot.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblTimeSlot.setText("Time Slot :");

        lblMaxPatientCount.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblMaxPatientCount.setText("Max Patient Count :");

        txtDoctorName.setFocusable(false);

        txtDoctorID.setFocusable(false);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblMaxPatientCount)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMaxPatientCount))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTimeSlot)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbldayName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDayName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDoctorID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblScheduleID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbScheduleId, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDoctorName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(711, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScheduleID)
                    .addComponent(cmbScheduleId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorName)
                    .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorID)
                    .addComponent(txtDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldayName)
                    .addComponent(txtDayName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeSlot)
                    .addComponent(txtTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxPatientCount)
                    .addComponent(txtMaxPatientCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbScheduleIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbScheduleIdItemStateChanged
        try {
            String scheduleID=(String) cmbScheduleId.getSelectedItem();
            SearchQueryDTO sea=ctrlQuery.getScheduleDetails(scheduleID);
            txtDoctorName.setText(sea.getDrName());
            txtDoctorID.setText(sea.getDrID());
            txtDayName.setText(sea.getDayName());
            txtTimeSlot.setText(sea.getTimeSlot());
            txtMaxPatientCount.setText(sea.getMaxPatientCount());
        } catch (Exception ex) {
            Logger.getLogger(ChangeSchedulePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmbScheduleIdItemStateChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       String scheduleID=(String) cmbScheduleId.getSelectedItem();
        ScheduleDTO schedule=new ScheduleDTO(
                scheduleID,
                txtDoctorID.getText(),
                txtDayName.getText(),
                txtTimeSlot.getText(),
                Integer.parseInt(txtMaxPatientCount.getText()));
        try {
            boolean result=ctrlSchedule.update(schedule);
            if (result){
                JOptionPane.showMessageDialog(this, "Schedule has been successfully Updated...!");
            }else{
                JOptionPane.showMessageDialog(this, "Schedule has not been Updated...!");
            }
        } catch (Exception ex) {
            Logger.getLogger(ChangeSchedulePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnUpdate;
    private com.jidesoft.swing.AutoCompletionComboBox cmbScheduleId;
    private javax.swing.JLabel lblDoctorID;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblMaxPatientCount;
    private javax.swing.JLabel lblScheduleID;
    private javax.swing.JLabel lblTimeSlot;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JLabel lbldayName;
    private javax.swing.JTextField txtDayName;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtMaxPatientCount;
    private javax.swing.JTextField txtTimeSlot;
    // End of variables declaration//GEN-END:variables
}
