/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.gdse41.doctorchannelingsystem.controller.ControllerFactory;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.DoctorController;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.HospitalController;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.QueryController;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.SpecialityController;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.impl.QueryControllerImpl;
import lk.ijse.gdse41.doctorchannelingsystem.dto.DoctorDTO;
import lk.ijse.gdse41.doctorchannelingsystem.dto.HospitalDTO;
import lk.ijse.gdse41.doctorchannelingsystem.dto.SearchQueryDTO;
import lk.ijse.gdse41.doctorchannelingsystem.dto.SpecialityDTO;

/**
 *
 * @author Binura Salindra
 */
public class ChangeDoctorPanel extends javax.swing.JPanel {
    private DoctorController ctrlDoctor;
    private SpecialityController ctrlSpeciality;
    private HospitalController ctrlHospital;
    private QueryController ctrlQuery;

    /**
     * Creates new form AddNewDoctorPanel
     */
    public ChangeDoctorPanel() {
        initComponents();
        ctrlQuery=(QueryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.QUERY);
        ctrlHospital=(HospitalController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.HOSPITAL);
        ctrlDoctor=(DoctorController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.DOCTOR);
        ctrlSpeciality=(SpecialityController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SPECIALITY);
        loadHospitalNames();
        loadSpecialityTypes();
        loadDoctorID();
        
    }
    
    private void loadHospitalNames(){
        ArrayList<String> hospitalNames;
        try {
             hospitalNames  = ctrlQuery.getAllHospitalNames();
             for (int i = 0; i < hospitalNames.size(); i++){
            cmbHospital.addItem(hospitalNames.get(i));
        }
        } catch (Exception ex) {
            Logger.getLogger(ChangeDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
	}
    private void loadSpecialityTypes(){
        ArrayList<String> specialityTypes=null;
        try {
            specialityTypes=ctrlQuery.getAllSpecialityTypes();
        } catch (Exception ex) {
            Logger.getLogger(ChangeDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         for (int i = 0; i < specialityTypes.size(); i++){
            cmbSpeciality.addItem(specialityTypes.get(i));
        }
    }
    private void loadDoctorID(){
        ArrayList<String> allDoctorIds=null;
        try {
            allDoctorIds=ctrlQuery.getAllDoctorId();
        } catch (Exception ex) {
            Logger.getLogger(ChangeDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         for (int i = 0; i < allDoctorIds.size(); i++){
            cmbDoctorID.addItem(allDoctorIds.get(i));
        }
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDocID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblTelNo = new javax.swing.JLabel();
        lblNewSpeciality = new javax.swing.JLabel();
        lblSpID = new javax.swing.JLabel();
        lblNewHospital = new javax.swing.JLabel();
        lblHosID = new javax.swing.JLabel();
        txtDoctorName = new javax.swing.JTextField();
        txtTelNo = new javax.swing.JTextField();
        cmbSpeciality = new com.jidesoft.swing.AutoCompletionComboBox();
        cmbHospital = new com.jidesoft.swing.AutoCompletionComboBox();
        txtSpecialityId = new javax.swing.JTextField();
        txtHospitalId = new javax.swing.JTextField();
        btnUpdate = new org.jdesktop.swingx.JXButton();
        btnAddNewSp = new org.jdesktop.swingx.JXButton();
        btnAddNewHo = new org.jdesktop.swingx.JXButton();
        lblTopic1 = new javax.swing.JLabel();
        pnlBaseSpHo = new javax.swing.JPanel();
        cmbDoctorID = new javax.swing.JComboBox<>();
        lblSpeciality = new javax.swing.JLabel();
        txtSpeciality = new javax.swing.JTextField();
        lblHospital = new javax.swing.JLabel();
        txtHospital = new javax.swing.JTextField();
        lblTopic2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblDocID.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDocID.setText("Doc ID :");

        lblName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblName.setText("Name :");

        lblTelNo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblTelNo.setText("Tel No :");

        lblNewSpeciality.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNewSpeciality.setText("Speciality :");

        lblSpID.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSpID.setText("Sp ID :");

        lblNewHospital.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNewHospital.setText("Hospital :");

        lblHosID.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblHosID.setText("Hos ID :");

        cmbSpeciality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbSpeciality.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSpecialityItemStateChanged(evt);
            }
        });

        cmbHospital.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbHospital.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbHospitalItemStateChanged(evt);
            }
        });

        txtSpecialityId.setFocusable(false);
        txtSpecialityId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialityIdActionPerformed(evt);
            }
        });

        txtHospitalId.setFocusable(false);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAddNewSp.setText("New");
        btnAddNewSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewSpMouseClicked(evt);
            }
        });

        btnAddNewHo.setText("New");
        btnAddNewHo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewHoMouseClicked(evt);
            }
        });

        lblTopic1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTopic1.setText("View & Change Doctor Details");

        pnlBaseSpHo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBaseSpHoLayout = new javax.swing.GroupLayout(pnlBaseSpHo);
        pnlBaseSpHo.setLayout(pnlBaseSpHoLayout);
        pnlBaseSpHoLayout.setHorizontalGroup(
            pnlBaseSpHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        pnlBaseSpHoLayout.setVerticalGroup(
            pnlBaseSpHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        cmbDoctorID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDoctorIDItemStateChanged(evt);
            }
        });

        lblSpeciality.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSpeciality.setText("Speciality :");

        txtSpeciality.setFocusable(false);

        lblHospital.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblHospital.setText("Hospital :");

        txtHospital.setFocusable(false);
        txtHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalActionPerformed(evt);
            }
        });

        lblTopic2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTopic2.setText("Change Hospital and Speciality");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDocID)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblTelNo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSpeciality)
                                .addComponent(lblHospital)
                                .addComponent(lblSpID)
                                .addComponent(lblHosID))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHospitalId)
                                .addComponent(txtSpecialityId)
                                .addComponent(txtHospital)
                                .addComponent(txtSpeciality))))
                    .addComponent(lblTopic2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblNewHospital)
                                    .addGap(15, 15, 15)
                                    .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblNewSpeciality)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddNewSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddNewHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBaseSpHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTopic1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocID)
                    .addComponent(cmbDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelNo)
                    .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpeciality)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHospital)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpID)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSpecialityId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHosID)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtHospitalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblTopic2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewSpeciality)
                    .addComponent(cmbSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewHospital)
                    .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBaseSpHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String doctorID=(String) cmbDoctorID.getSelectedItem();
        try {
            DoctorDTO doctor=new DoctorDTO(
                    doctorID,
                    txtSpecialityId.getText(),
                    txtHospitalId.getText(),
                    txtDoctorName.getText(),
                    txtTelNo.getText());
            
            boolean result = ctrlDoctor.update(doctor);
            if (result){
                JOptionPane.showMessageDialog(this, "Doctor has been successfully Updated...!");
            }else{
                JOptionPane.showMessageDialog(this, "Doctor has not been Updated...!");
            }
        } catch (Exception ex) {
            Logger.getLogger(ChangeDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
      
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cmbSpecialityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSpecialityItemStateChanged
       String id=(String) cmbSpeciality.getSelectedItem();
        try {
            SpecialityDTO speciality=ctrlSpeciality.search(id);
            txtSpecialityId.setText(speciality.getSpID());
        } catch (Exception ex) {
            Logger.getLogger(ChangeDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbSpecialityItemStateChanged

    private void cmbHospitalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbHospitalItemStateChanged
      String id=(String) cmbHospital.getSelectedItem();
        try {
            HospitalDTO hospital=ctrlHospital.search(id);
            txtHospitalId.setText(hospital.gethID());
        } catch (Exception ex) {
            Logger.getLogger(ChangeDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbHospitalItemStateChanged

    private void btnAddNewSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewSpMouseClicked
      AddNewSpecialityPanel s1=new AddNewSpecialityPanel();
      s1.setSize(pnlBaseSpHo.getSize());
      pnlBaseSpHo.removeAll();
      pnlBaseSpHo.add(s1);
      pnlBaseSpHo.revalidate();
      pnlBaseSpHo.repaint();
      s1.show();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddNewSpMouseClicked

    private void btnAddNewHoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewHoMouseClicked
      AddNewHospitalPanel s1=new AddNewHospitalPanel();
      s1.setSize(pnlBaseSpHo.getSize());
      pnlBaseSpHo.removeAll();
      pnlBaseSpHo.add(s1);
      pnlBaseSpHo.revalidate();
      pnlBaseSpHo.repaint();
      s1.show();
    
    }//GEN-LAST:event_btnAddNewHoMouseClicked

    private void cmbDoctorIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDoctorIDItemStateChanged
     String doctorId=(String) cmbDoctorID.getSelectedItem();
        try {
            SearchQueryDTO search=ctrlQuery.getAllDoctorDetails(doctorId);
            txtDoctorName.setText(search.getDrName());
            txtTelNo.setText(search.getDrTelno());
            txtSpeciality.setText(search.getSpType());
            txtHospital.setText(search.gethName());
            txtSpecialityId.setText(search.getSpID());
            txtHospitalId.setText(search.gethID());
        } catch (Exception ex) {
            Logger.getLogger(ChangeDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_cmbDoctorIDItemStateChanged

    private void txtSpecialityIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialityIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialityIdActionPerformed

    private void txtHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnAddNewHo;
    private org.jdesktop.swingx.JXButton btnAddNewSp;
    private org.jdesktop.swingx.JXButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDoctorID;
    private com.jidesoft.swing.AutoCompletionComboBox cmbHospital;
    private com.jidesoft.swing.AutoCompletionComboBox cmbSpeciality;
    private javax.swing.JLabel lblDocID;
    private javax.swing.JLabel lblHosID;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewHospital;
    private javax.swing.JLabel lblNewSpeciality;
    private javax.swing.JLabel lblSpID;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JLabel lblTelNo;
    private javax.swing.JLabel lblTopic1;
    private javax.swing.JLabel lblTopic2;
    private javax.swing.JPanel pnlBaseSpHo;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtHospitalId;
    private javax.swing.JTextField txtSpeciality;
    private javax.swing.JTextField txtSpecialityId;
    private javax.swing.JTextField txtTelNo;
    // End of variables declaration//GEN-END:variables
}
