/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.gdse41.doctorchannelingsystem.controller.ControllerFactory;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.UserController;
import lk.ijse.gdse41.doctorchannelingsystem.dto.UserDTO;
import lk.ijse.gdse41.doctorchannelingsystem.view.MainFrame;

/**
 *
 * @author Binura Salindra
 */
public class ChangeUserPasswordPanel extends javax.swing.JPanel {
    private UserController ctrlUser;

    /**
     * Creates new form ChangeUserPasswordPanel
     */
    public ChangeUserPasswordPanel() {
        initComponents();
        ctrlUser=(UserController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.USER);
        lblMessage.setVisible(false);
        btnChange.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        lblConfrimPassword = new javax.swing.JLabel();
        btnChange = new org.jdesktop.swingx.JXButton();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtConfrimPassword = new javax.swing.JPasswordField();
        lblMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTopic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTopic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Remove Key_26px.png"))); // NOI18N
        lblTopic.setText("Change User Password");

        lblUserName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblUserName.setText("User Name :");

        lblpassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblpassword.setText("Password :");

        lblNewPassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNewPassword.setText("New Password :");

        lblConfrimPassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblConfrimPassword.setText("Confrim Password :");

        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPasswordActionPerformed(evt);
            }
        });

        txtConfrimPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfrimPasswordActionPerformed(evt);
            }
        });

        lblMessage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblConfrimPassword)
                            .addGap(24, 24, 24)
                            .addComponent(txtConfrimPassword))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTopic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserName)
                                    .addComponent(lblpassword)
                                    .addComponent(lblNewPassword))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(txtPassword)
                                    .addComponent(txtNewPassword))))))
                .addGap(18, 18, 18)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopic)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPassword)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfrimPassword)
                    .addComponent(txtConfrimPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
       txtPassword.requestFocus();
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
       UserDTO dt0=new UserDTO(txtUserName.getText(),txtPassword.getText());
        try {
            boolean login=ctrlUser.login(dt0);
            if(login){
                txtNewPassword.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this,"Incorrect username or password");
            }
        } catch (Exception ex) {
            Logger.getLogger(ChangeUserPasswordPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed
        txtConfrimPassword.requestFocus();
    }//GEN-LAST:event_txtNewPasswordActionPerformed

    private void txtConfrimPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfrimPasswordActionPerformed
       char[] newPassword=txtNewPassword.getPassword();
       char[] confirmPassword=txtConfrimPassword.getPassword();
       boolean equals = new String(newPassword).equals(new String(confirmPassword));
       if(equals){
           lblMessage.setText("Match");
           lblMessage.setForeground(Color.BLUE);
           lblMessage.setVisible(true);
           btnChange.setEnabled(true);
           btnChange.requestFocus();
       }else{
           lblMessage.setText("Password not match");
           lblMessage.setForeground(Color.RED);
           lblMessage.setVisible(true);
       }
    }//GEN-LAST:event_txtConfrimPasswordActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
       UserDTO dt=new UserDTO(txtUserName.getText(),txtConfrimPassword.getText());
        try {
            boolean result=ctrlUser.update(dt);
            if(result){
                JOptionPane.showMessageDialog(this,"Password is Changed");
            }else{
                JOptionPane.showMessageDialog(this,"Password is not changed");
            }
        } catch (Exception ex) {
            Logger.getLogger(ChangeUserPasswordPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnChange;
    private javax.swing.JLabel lblConfrimPassword;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JPasswordField txtConfrimPassword;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
