/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

/**
 *
 * @author Binura Salindra
 */
public class HospitalPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalPanel
     */
    public HospitalPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddNewHospital = new javax.swing.JLabel();
        lblChangeHospital = new javax.swing.JLabel();
        lblRemoveHospital = new javax.swing.JLabel();
        pnlHospitalBase = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblAddNewHospital.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblAddNewHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Add List_26px.png"))); // NOI18N
        lblAddNewHospital.setText("Add New Hospital |");
        lblAddNewHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddNewHospitalMouseClicked(evt);
            }
        });

        lblChangeHospital.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblChangeHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Edit Property_26px.png"))); // NOI18N
        lblChangeHospital.setText("Change Hospital Details |");
        lblChangeHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeHospitalMouseClicked(evt);
            }
        });

        lblRemoveHospital.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblRemoveHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Trash_26px.png"))); // NOI18N
        lblRemoveHospital.setText("Remove Hospital");
        lblRemoveHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveHospitalMouseClicked(evt);
            }
        });

        pnlHospitalBase.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/hospital.png"))); // NOI18N

        javax.swing.GroupLayout pnlHospitalBaseLayout = new javax.swing.GroupLayout(pnlHospitalBase);
        pnlHospitalBase.setLayout(pnlHospitalBaseLayout);
        pnlHospitalBaseLayout.setHorizontalGroup(
            pnlHospitalBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHospitalBaseLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHospitalBaseLayout.setVerticalGroup(
            pnlHospitalBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHospitalBaseLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel3)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHospitalBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddNewHospital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblChangeHospital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRemoveHospital)
                        .addGap(0, 505, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddNewHospital)
                    .addComponent(lblChangeHospital)
                    .addComponent(lblRemoveHospital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHospitalBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddNewHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewHospitalMouseClicked
       AddNewHospitalPanel1 ad=new AddNewHospitalPanel1();
       ad.setSize(pnlHospitalBase.getSize());
       pnlHospitalBase.removeAll();
       pnlHospitalBase.add(ad);
       pnlHospitalBase.revalidate();
       pnlHospitalBase.repaint();
    }//GEN-LAST:event_lblAddNewHospitalMouseClicked

    private void lblChangeHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeHospitalMouseClicked
       ChangeHospitalPanel ad=new ChangeHospitalPanel();
       ad.setSize(pnlHospitalBase.getSize());
       pnlHospitalBase.removeAll();
       pnlHospitalBase.add(ad);
       pnlHospitalBase.revalidate();
       pnlHospitalBase.repaint();
    }//GEN-LAST:event_lblChangeHospitalMouseClicked

    private void lblRemoveHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveHospitalMouseClicked
       RemoveHospitalPanel ad=new RemoveHospitalPanel();
       ad.setSize(pnlHospitalBase.getSize());
       pnlHospitalBase.removeAll();
       pnlHospitalBase.add(ad);
       pnlHospitalBase.revalidate();
       pnlHospitalBase.repaint();
    }//GEN-LAST:event_lblRemoveHospitalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddNewHospital;
    private javax.swing.JLabel lblChangeHospital;
    private javax.swing.JLabel lblRemoveHospital;
    private javax.swing.JPanel pnlHospitalBase;
    // End of variables declaration//GEN-END:variables
}
