/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

/**
 *
 * @author Binura Salindra
 */
public class MakeNewAppointmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form MakeNewAppointmentPanel
     */
    public MakeNewAppointmentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearchType = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        lblHospital = new javax.swing.JLabel();
        lblSpeciality = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        pnlMakePanelBase = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1090, 620));

        lblSearchType.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSearchType.setText("Select Search Type :");

        lblDoctor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Doctor Male_48px.png"))); // NOI18N
        lblDoctor.setText("Doctor");
        lblDoctor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoctorMouseClicked(evt);
            }
        });

        lblHospital.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Hospital_40px.png"))); // NOI18N
        lblHospital.setText("Hospital");
        lblHospital.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHospitalMouseClicked(evt);
            }
        });

        lblSpeciality.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSpeciality.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Speciality_48px.png"))); // NOI18N
        lblSpeciality.setText("Speciality");
        lblSpeciality.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblSpeciality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpecialityMouseClicked(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Tear Off Calendar_48px.png"))); // NOI18N
        lblDate.setText("Date");
        lblDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDateMouseClicked(evt);
            }
        });

        pnlMakePanelBase.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlMakePanelBaseLayout = new javax.swing.GroupLayout(pnlMakePanelBase);
        pnlMakePanelBase.setLayout(pnlMakePanelBaseLayout);
        pnlMakePanelBaseLayout.setHorizontalGroup(
            pnlMakePanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMakePanelBaseLayout.setVerticalGroup(
            pnlMakePanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMakePanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 379, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctor)
                    .addComponent(lblHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpeciality)
                    .addComponent(lblDate)
                    .addComponent(lblSearchType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMakePanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoctorMouseClicked
        SearchByDoctorPanel ad=new SearchByDoctorPanel();
        ad.setSize(pnlMakePanelBase.getSize());
        pnlMakePanelBase.removeAll();
        pnlMakePanelBase.add(ad);
        pnlMakePanelBase.revalidate();
        pnlMakePanelBase.repaint();
        ad.show();
    }//GEN-LAST:event_lblDoctorMouseClicked

    private void lblHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHospitalMouseClicked
      SearchByHospitalPanel sw=new SearchByHospitalPanel();
      sw.setSize(pnlMakePanelBase.getSize());
      pnlMakePanelBase.removeAll();
      pnlMakePanelBase.add(sw);
      pnlMakePanelBase.revalidate();
      pnlMakePanelBase.repaint();
      sw.show();
    }//GEN-LAST:event_lblHospitalMouseClicked

    private void lblSpecialityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpecialityMouseClicked
       SearchBySpecialityPanel1 fd=new SearchBySpecialityPanel1();
       fd.setSize(pnlMakePanelBase.getSize());
       pnlMakePanelBase.removeAll();
       pnlMakePanelBase.add(fd);
       pnlMakePanelBase.revalidate();
       pnlMakePanelBase.repaint();
       fd.show();
    }//GEN-LAST:event_lblSpecialityMouseClicked

    private void lblDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDateMouseClicked
       SearchByDatePanel sd=new SearchByDatePanel();
       sd.setSize(pnlMakePanelBase.getSize());
       pnlMakePanelBase.removeAll();
       pnlMakePanelBase.add(sd);
       pnlMakePanelBase.revalidate();
       pnlMakePanelBase.repaint();
       sd.show();
    }//GEN-LAST:event_lblDateMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblSearchType;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JPanel pnlMakePanelBase;
    // End of variables declaration//GEN-END:variables
}
