/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

/**
 *
 * @author Binura Salindra
 */
public class NewSchedulePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewSchedulePanel
     */
    public NewSchedulePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMakeNewSchedule = new javax.swing.JLabel();
        lblChangeScheduleDetails = new javax.swing.JLabel();
        lblRemoveSchedule = new javax.swing.JLabel();
        pnlScheduleBase = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblMakeNewSchedule.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblMakeNewSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Add List_26px.png"))); // NOI18N
        lblMakeNewSchedule.setText("Make New Schedule  |");
        lblMakeNewSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMakeNewScheduleMouseClicked(evt);
            }
        });

        lblChangeScheduleDetails.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblChangeScheduleDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Edit Property_26px.png"))); // NOI18N
        lblChangeScheduleDetails.setText("Change Schedule Details  |");
        lblChangeScheduleDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeScheduleDetailsMouseClicked(evt);
            }
        });

        lblRemoveSchedule.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblRemoveSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Trash_26px.png"))); // NOI18N
        lblRemoveSchedule.setText("Remove Schedule");
        lblRemoveSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveScheduleMouseClicked(evt);
            }
        });

        pnlScheduleBase.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/clockGraphic.png"))); // NOI18N

        javax.swing.GroupLayout pnlScheduleBaseLayout = new javax.swing.GroupLayout(pnlScheduleBase);
        pnlScheduleBase.setLayout(pnlScheduleBaseLayout);
        pnlScheduleBaseLayout.setHorizontalGroup(
            pnlScheduleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleBaseLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlScheduleBaseLayout.setVerticalGroup(
            pnlScheduleBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleBaseLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlScheduleBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMakeNewSchedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChangeScheduleDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRemoveSchedule)
                        .addGap(0, 469, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMakeNewSchedule)
                    .addComponent(lblChangeScheduleDetails)
                    .addComponent(lblRemoveSchedule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlScheduleBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblMakeNewScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeNewScheduleMouseClicked
        MakeNewSchedule mk=new MakeNewSchedule();
        mk.setSize(pnlScheduleBase.getSize());
        pnlScheduleBase.removeAll();
        pnlScheduleBase.add(mk);
        pnlScheduleBase.revalidate();
        pnlScheduleBase.repaint();
        mk.show();
    }//GEN-LAST:event_lblMakeNewScheduleMouseClicked

    private void lblChangeScheduleDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeScheduleDetailsMouseClicked
        ChangeSchedulePanel mk=new ChangeSchedulePanel();
        mk.setSize(pnlScheduleBase.getSize());
        pnlScheduleBase.removeAll();
        pnlScheduleBase.add(mk);
        pnlScheduleBase.revalidate();
        pnlScheduleBase.repaint();
        mk.show();
    }//GEN-LAST:event_lblChangeScheduleDetailsMouseClicked

    private void lblRemoveScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveScheduleMouseClicked
        RemoveSchedulePanel mk=new RemoveSchedulePanel();
        mk.setSize(pnlScheduleBase.getSize());
        pnlScheduleBase.removeAll();
        pnlScheduleBase.add(mk);
        pnlScheduleBase.revalidate();
        pnlScheduleBase.repaint();
        mk.show();
    }//GEN-LAST:event_lblRemoveScheduleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblChangeScheduleDetails;
    private javax.swing.JLabel lblMakeNewSchedule;
    private javax.swing.JLabel lblRemoveSchedule;
    private javax.swing.JPanel pnlScheduleBase;
    // End of variables declaration//GEN-END:variables
}
