/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

/**
 *
 * @author Binura Salindra
 */
public class PatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanel
     */
    public PatientPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewAllPatients = new javax.swing.JLabel();
        lblChangePatientDetails = new javax.swing.JLabel();
        pnlPatientBase = new javax.swing.JPanel();
        lblRemovePatientDetails = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblViewAllPatients.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblViewAllPatients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/View Details_26px.png"))); // NOI18N
        lblViewAllPatients.setText("View All Patients  |");
        lblViewAllPatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewAllPatientsMouseClicked(evt);
            }
        });

        lblChangePatientDetails.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblChangePatientDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Edit Property_26px.png"))); // NOI18N
        lblChangePatientDetails.setText("Change Patient Details |");
        lblChangePatientDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangePatientDetailsMouseClicked(evt);
            }
        });

        pnlPatientBase.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlPatientBaseLayout = new javax.swing.GroupLayout(pnlPatientBase);
        pnlPatientBase.setLayout(pnlPatientBaseLayout);
        pnlPatientBaseLayout.setHorizontalGroup(
            pnlPatientBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        pnlPatientBaseLayout.setVerticalGroup(
            pnlPatientBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        lblRemovePatientDetails.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblRemovePatientDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Edit Property_26px.png"))); // NOI18N
        lblRemovePatientDetails.setText("Remove Patient Details ");
        lblRemovePatientDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemovePatientDetailsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPatientBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblViewAllPatients)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChangePatientDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRemovePatientDetails)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAllPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChangePatientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemovePatientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPatientBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblViewAllPatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllPatientsMouseClicked
     ViewPatientPanel v1=new ViewPatientPanel();
     v1.setSize(pnlPatientBase.getSize());
     pnlPatientBase.removeAll();
     pnlPatientBase.add(v1);
     pnlPatientBase.revalidate();
     pnlPatientBase.repaint();
     v1.show();
    }//GEN-LAST:event_lblViewAllPatientsMouseClicked

    private void lblChangePatientDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangePatientDetailsMouseClicked
      ChangePatientDetailPanel c1=new ChangePatientDetailPanel();
      c1.setSize(pnlPatientBase.getSize());
      pnlPatientBase.removeAll();
      pnlPatientBase.add(c1);
      pnlPatientBase.revalidate();
      pnlPatientBase.repaint();
      c1.show();
    }//GEN-LAST:event_lblChangePatientDetailsMouseClicked

    private void lblRemovePatientDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemovePatientDetailsMouseClicked
      RemovePatientPanel c1=new RemovePatientPanel();
      c1.setSize(pnlPatientBase.getSize());
      pnlPatientBase.removeAll();
      pnlPatientBase.add(c1);
      pnlPatientBase.revalidate();
      pnlPatientBase.repaint();
      c1.show();
    }//GEN-LAST:event_lblRemovePatientDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblChangePatientDetails;
    private javax.swing.JLabel lblRemovePatientDetails;
    private javax.swing.JLabel lblViewAllPatients;
    private javax.swing.JPanel pnlPatientBase;
    // End of variables declaration//GEN-END:variables
}
