/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gdse41.doctorchannelingsystem.controller.ControllerFactory;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.QueryController;
import lk.ijse.gdse41.doctorchannelingsystem.dto.ScheduleQueryDTO;

/**
 *
 * @author Binura Salindra
 */
public class SearchByHospitalPanel extends javax.swing.JPanel {
    private QueryController ctrlQuery;
    

    /**
     * Creates new form SearchByDoctorPanel
     */
    public SearchByHospitalPanel() {
        initComponents();
        pnlSearchHospitalBase.setVisible(false);
        ctrlQuery=(QueryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.QUERY);
        loadHospitalNames();
        
    }
    private void loadHospitalNames(){
        try {
            ArrayList<String>hospitalNames = ctrlQuery.getAllHospitalNames();
            for (int i = 0; i < hospitalNames.size(); i++){
                cmbHospital.addItem(hospitalNames.get(i));
            }
        }catch(Exception ex) {
            Logger.getLogger(SearchByHospitalPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
        
      


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        lblHospitalName = new javax.swing.JLabel();
        cmbHospital = new com.jidesoft.swing.AutoCompletionComboBox();
        btnSearch = new org.jdesktop.swingx.JXButton();
        pnlSearchHospitalBase = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchByHospital = new org.jdesktop.swingx.JXTable();
        lblMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTopic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTopic.setText("Search By Hospital :");

        lblHospitalName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblHospitalName.setText("Hospital  :");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        pnlSearchHospitalBase.setBackground(new java.awt.Color(255, 255, 255));

        tblSearchByHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Doctor", "Hospital", "Speciality", "Schedule", "Patient Count", "Day", "Time Slot"
            }
        ));
        tblSearchByHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchByHospitalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearchByHospital);

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMessage.setText("Tip : Select suitable row on the table");

        javax.swing.GroupLayout pnlSearchHospitalBaseLayout = new javax.swing.GroupLayout(pnlSearchHospitalBase);
        pnlSearchHospitalBase.setLayout(pnlSearchHospitalBaseLayout);
        pnlSearchHospitalBaseLayout.setHorizontalGroup(
            pnlSearchHospitalBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchHospitalBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlSearchHospitalBaseLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchHospitalBaseLayout.setVerticalGroup(
            pnlSearchHospitalBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchHospitalBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSearchHospitalBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 763, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalName)
                    .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlSearchHospitalBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String hName=(String) cmbHospital.getSelectedItem();
        DefaultTableModel dtm=(DefaultTableModel) tblSearchByHospital.getModel();
        dtm.setRowCount(0);
        try {
            ArrayList<ScheduleQueryDTO> allSearchIndex=ctrlQuery.searchByHospital(hName);
            for(ScheduleQueryDTO get:allSearchIndex){
                Object []row={get.getDrName(),get.gethName(),get.getSpType(),get.getScID(),get.getMaxPatientCount(),get.getDayName(),get.getTimeSlot()};
                dtm.addRow(row); 
        }
        } catch (Exception ex) {
            Logger.getLogger(SearchByHospitalPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlSearchHospitalBase.setVisible(true);
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblSearchByHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchByHospitalMouseClicked
      DefaultTableModel dtm=(DefaultTableModel) tblSearchByHospital.getModel();
        String scheduleId=(String) tblSearchByHospital.getValueAt(tblSearchByHospital.getSelectedRow(), 3);
        String scheduleDay=(String) tblSearchByHospital.getValueAt(tblSearchByHospital.getSelectedRow(), 5);
        SelectDatePanel ap=new SelectDatePanel(scheduleId,scheduleDay);
        ap.setSize(pnlSearchHospitalBase.getSize());
        pnlSearchHospitalBase.removeAll();
        pnlSearchHospitalBase.add(ap);
        pnlSearchHospitalBase.revalidate();
        pnlSearchHospitalBase.repaint();
        ap.show();
    }//GEN-LAST:event_tblSearchByHospitalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnSearch;
    private com.jidesoft.swing.AutoCompletionComboBox cmbHospital;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JPanel pnlSearchHospitalBase;
    private org.jdesktop.swingx.JXTable tblSearchByHospital;
    // End of variables declaration//GEN-END:variables
}
