/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gdse41.doctorchannelingsystem.controller.ControllerFactory;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.QueryController;
import lk.ijse.gdse41.doctorchannelingsystem.dto.ScheduleQueryDTO;

/**
 *
 * @author Binura Salindra
 */
public class SearchBySpecialityPanel1 extends javax.swing.JPanel {
    private QueryController ctrlQuery;
    

    /**
     * Creates new form SearchByDoctorPanel
     */
    public SearchBySpecialityPanel1() {
        initComponents();
        pnlSearchSpecialitylBase.setVisible(false);
        ctrlQuery=(QueryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.QUERY);
        loadSpecialityTypes();
        
    }
    
    private void loadSpecialityTypes(){
        ArrayList<String> specialityTypes=null;
        
        try {
            specialityTypes=ctrlQuery.getAllSpecialityTypes();
        } catch (Exception ex) {
            Logger.getLogger(SearchBySpecialityPanel1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         for (int i = 0; i < specialityTypes.size(); i++){
            cmbSpeciality.addItem(specialityTypes.get(i));
        }
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        lblSpecialityType = new javax.swing.JLabel();
        cmbSpeciality = new com.jidesoft.swing.AutoCompletionComboBox();
        btnSearch = new org.jdesktop.swingx.JXButton();
        pnlSearchSpecialitylBase = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchBySpeciality = new org.jdesktop.swingx.JXTable();
        lblMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTopic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTopic.setText("Search By Speciality :");

        lblSpecialityType.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSpecialityType.setText("Speciality  :");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        pnlSearchSpecialitylBase.setBackground(new java.awt.Color(255, 255, 255));

        tblSearchBySpeciality.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Doctor", "Hospital", "Speciality", "Schedule", "Patient Count", "Day", "Time Slot"
            }
        ));
        tblSearchBySpeciality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchBySpecialityMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearchBySpeciality);

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMessage.setText("Tip : Select suitable row on the table");

        javax.swing.GroupLayout pnlSearchSpecialitylBaseLayout = new javax.swing.GroupLayout(pnlSearchSpecialitylBase);
        pnlSearchSpecialitylBase.setLayout(pnlSearchSpecialitylBaseLayout);
        pnlSearchSpecialitylBaseLayout.setHorizontalGroup(
            pnlSearchSpecialitylBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchSpecialitylBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlSearchSpecialitylBaseLayout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchSpecialitylBaseLayout.setVerticalGroup(
            pnlSearchSpecialitylBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchSpecialitylBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSearchSpecialitylBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSpecialityType, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecialityType)
                    .addComponent(cmbSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(pnlSearchSpecialitylBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String spType=(String) cmbSpeciality.getSelectedItem();
        DefaultTableModel dtm=(DefaultTableModel) tblSearchBySpeciality.getModel();
        dtm.setRowCount(0);
        try {
            ArrayList<ScheduleQueryDTO> allSearchIndex=ctrlQuery.searchBySpeciality(spType);
            for(ScheduleQueryDTO get:allSearchIndex){
                Object []row={get.getDrName(),get.gethName(),get.getSpType(),get.getScID(),get.getMaxPatientCount(),get.getDayName(),get.getTimeSlot()};
                dtm.addRow(row); 
        }
        } catch (Exception ex) {
            Logger.getLogger(SearchByHospitalPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlSearchSpecialitylBase.setVisible(true);
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblSearchBySpecialityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchBySpecialityMouseClicked
        DefaultTableModel dtm=(DefaultTableModel) tblSearchBySpeciality.getModel();
        String scheduleId=(String) tblSearchBySpeciality.getValueAt(tblSearchBySpeciality.getSelectedRow(), 3);
        String scheduleDay=(String) tblSearchBySpeciality.getValueAt(tblSearchBySpeciality.getSelectedRow(), 5);
        SelectDatePanel ap=new SelectDatePanel(scheduleId,scheduleDay);
        ap.setSize(pnlSearchSpecialitylBase.getSize());
        pnlSearchSpecialitylBase.removeAll();
        pnlSearchSpecialitylBase.add(ap);
        pnlSearchSpecialitylBase.revalidate();
        pnlSearchSpecialitylBase.repaint();
        ap.show();
    }//GEN-LAST:event_tblSearchBySpecialityMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnSearch;
    private com.jidesoft.swing.AutoCompletionComboBox cmbSpeciality;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSpecialityType;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JPanel pnlSearchSpecialitylBase;
    private org.jdesktop.swingx.JXTable tblSearchBySpeciality;
    // End of variables declaration//GEN-END:variables
}
