/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.gdse41.doctorchannelingsystem.controller.ControllerFactory;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.DoctorController;
import lk.ijse.gdse41.doctorchannelingsystem.controller.custom.QueryController;
import lk.ijse.gdse41.doctorchannelingsystem.dto.DoctorDTO;
import lk.ijse.gdse41.doctorchannelingsystem.dto.ScheduleDTO;
import lk.ijse.gdse41.doctorchannelingsystem.dto.ScheduleQueryDTO;

/**
 *
 * @author Binura Salindra
 */
public class SearchByDoctorPanel extends javax.swing.JPanel {
    private QueryController ctrlQuery;
    private DoctorController ctrlDoctor;

    /**
     * Creates new form SearchByDoctorPanel
     */
    public SearchByDoctorPanel() {
        initComponents();
        pnlSearchDoctorBase.setVisible(false);
        ctrlQuery=(QueryController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.QUERY);
        ctrlDoctor=(DoctorController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.DOCTOR);
        loadDoctorNames();
    }
    private void loadDoctorNames(){
        try {
            ArrayList<String> doctorNames=ctrlQuery.getAllDoctorNames();
            for (int i = 0; i < doctorNames.size(); i++) {
                cmbDoctor.addItem(doctorNames.get(i));
            }

        } catch (Exception ex) {
            Logger.getLogger(SearchByDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static void main(String[] args) {
        new SearchByDoctorPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        cmbDoctor = new com.jidesoft.swing.AutoCompletionComboBox();
        txtDrID = new javax.swing.JTextField();
        btnSearch = new org.jdesktop.swingx.JXButton();
        pnlSearchDoctorBase = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchByDoctor = new org.jdesktop.swingx.JXTable();
        lblMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTopic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTopic.setText("Search By Doctor :");

        lblDoctorName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDoctorName.setText("Doctor Name :");

        cmbDoctor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDoctorItemStateChanged(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        pnlSearchDoctorBase.setBackground(new java.awt.Color(255, 255, 255));

        tblSearchByDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Doctor", "Hospital", "Speciality", "Schedule", "Patient Count", "Day", "Time Slot"
            }
        ));
        tblSearchByDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchByDoctorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearchByDoctor);

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMessage.setText("Tip : Select suitable row on the table");

        javax.swing.GroupLayout pnlSearchDoctorBaseLayout = new javax.swing.GroupLayout(pnlSearchDoctorBase);
        pnlSearchDoctorBase.setLayout(pnlSearchDoctorBaseLayout);
        pnlSearchDoctorBaseLayout.setHorizontalGroup(
            pnlSearchDoctorBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchDoctorBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlSearchDoctorBaseLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchDoctorBaseLayout.setVerticalGroup(
            pnlSearchDoctorBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchDoctorBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSearchDoctorBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDoctorName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtDrID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorName)
                    .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDrID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pnlSearchDoctorBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDoctorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDoctorItemStateChanged
        String id=(String) cmbDoctor.getSelectedItem();
        DoctorDTO  doctor = null;
        try {
            doctor = ctrlDoctor.search(id);
        } catch (Exception ex) {
            Logger.getLogger(SearchByDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtDrID.setText(doctor.getDrID());
        
    }//GEN-LAST:event_cmbDoctorItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String key=txtDrID.getText();
        DefaultTableModel dtm=(DefaultTableModel) tblSearchByDoctor.getModel();
        dtm.setRowCount(0);
        try {
            ArrayList<ScheduleQueryDTO> allSearchIndex=ctrlQuery.searchByDoctor(key);
            for(ScheduleQueryDTO get:allSearchIndex){
                Object []row={get.getDrName(),get.gethName(),get.getSpType(),get.getScID(),get.getMaxPatientCount(),get.getDayName(),get.getTimeSlot()};
                dtm.addRow(row); 
        }
        } catch (Exception ex) {
            Logger.getLogger(SearchByDoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlSearchDoctorBase.setVisible(true);
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblSearchByDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchByDoctorMouseClicked
        DefaultTableModel dtm=(DefaultTableModel) tblSearchByDoctor.getModel();
        String scheduleId=(String) tblSearchByDoctor.getValueAt(tblSearchByDoctor.getSelectedRow(), 3);
        String scheduleDay=(String) tblSearchByDoctor.getValueAt(tblSearchByDoctor.getSelectedRow(), 5);
        SelectDatePanel ap=new SelectDatePanel(scheduleId,scheduleDay);
       
        ap.setSize(pnlSearchDoctorBase.getSize());
        pnlSearchDoctorBase.removeAll();
        pnlSearchDoctorBase.add(ap);
        pnlSearchDoctorBase.revalidate();
        pnlSearchDoctorBase.repaint();
        ap.show();
    }//GEN-LAST:event_tblSearchByDoctorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnSearch;
    private com.jidesoft.swing.AutoCompletionComboBox cmbDoctor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JPanel pnlSearchDoctorBase;
    private org.jdesktop.swingx.JXTable tblSearchByDoctor;
    private javax.swing.JTextField txtDrID;
    // End of variables declaration//GEN-END:variables
}
