/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.gdse41.doctorchannelingsystem.view.panel;

/**
 *
 * @author Binura Salindra
 */
public class SpecialityPanel extends javax.swing.JPanel {

    /**
     * Creates new form SpecialityPanel
     */
    public SpecialityPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddNewSpeciality = new javax.swing.JLabel();
        lblChangeSpeciality = new javax.swing.JLabel();
        lblRemoveSpeciality = new javax.swing.JLabel();
        pnlSpecialityBase = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblAddNewSpeciality.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblAddNewSpeciality.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Add List_26px.png"))); // NOI18N
        lblAddNewSpeciality.setText("Add New Speciality |");
        lblAddNewSpeciality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddNewSpecialityMouseClicked(evt);
            }
        });

        lblChangeSpeciality.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblChangeSpeciality.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Edit Property_26px.png"))); // NOI18N
        lblChangeSpeciality.setText("Change Speciality Details |");
        lblChangeSpeciality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeSpecialityMouseClicked(evt);
            }
        });

        lblRemoveSpeciality.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblRemoveSpeciality.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/Trash_26px.png"))); // NOI18N
        lblRemoveSpeciality.setText("Remove Speciality");
        lblRemoveSpeciality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveSpecialityMouseClicked(evt);
            }
        });

        pnlSpecialityBase.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/gdse41/doctorchannelingsystem/resources/diploma_11600.png"))); // NOI18N

        javax.swing.GroupLayout pnlSpecialityBaseLayout = new javax.swing.GroupLayout(pnlSpecialityBase);
        pnlSpecialityBase.setLayout(pnlSpecialityBaseLayout);
        pnlSpecialityBaseLayout.setHorizontalGroup(
            pnlSpecialityBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSpecialityBaseLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSpecialityBaseLayout.setVerticalGroup(
            pnlSpecialityBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSpecialityBaseLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel3)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSpecialityBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddNewSpeciality)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChangeSpeciality)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRemoveSpeciality)
                        .addGap(0, 480, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddNewSpeciality)
                    .addComponent(lblChangeSpeciality)
                    .addComponent(lblRemoveSpeciality))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSpecialityBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddNewSpecialityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewSpecialityMouseClicked
        AddNewSpecialityPanel1 ad=new AddNewSpecialityPanel1();
        ad.setSize(pnlSpecialityBase.getSize());
        pnlSpecialityBase.removeAll();
        pnlSpecialityBase.add(ad);
        pnlSpecialityBase.revalidate();
        pnlSpecialityBase.repaint();
        ad.show();
    }//GEN-LAST:event_lblAddNewSpecialityMouseClicked

    private void lblChangeSpecialityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeSpecialityMouseClicked
        ChangeSpecialityPanel ad=new ChangeSpecialityPanel();
        ad.setSize(pnlSpecialityBase.getSize());
        pnlSpecialityBase.removeAll();
        pnlSpecialityBase.add(ad);
        pnlSpecialityBase.revalidate();
        pnlSpecialityBase.repaint();
        ad.show();
    }//GEN-LAST:event_lblChangeSpecialityMouseClicked

    private void lblRemoveSpecialityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveSpecialityMouseClicked
        RemoveSpecialityPanel ad=new RemoveSpecialityPanel();
        ad.setSize(pnlSpecialityBase.getSize());
        pnlSpecialityBase.removeAll();
        pnlSpecialityBase.add(ad);
        pnlSpecialityBase.revalidate();
        pnlSpecialityBase.repaint();
        ad.show();
    }//GEN-LAST:event_lblRemoveSpecialityMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddNewSpeciality;
    private javax.swing.JLabel lblChangeSpeciality;
    private javax.swing.JLabel lblRemoveSpeciality;
    private javax.swing.JPanel pnlSpecialityBase;
    // End of variables declaration//GEN-END:variables
}
